version: "3.9"

services: 
    jenkins:
        privileged: true
        container_name: jenkins
        build:
            context: .
            target: pipeline
        env_file:
            - .env
        ports:
            - "8001:8080"
            - "50000:50000"
        volumes: 
            - jenkins_vol:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks: 
            - pipeline
volumes:
    jenkins_vol:
networks: 
    pipeline:
